# Generated by Django 3.2.9 on 2021-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211105_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='characteristic',
            new_name='code_charact_fk',
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='code_charact',
            field=models.CharField(default='', max_length=2),
        ),
    ]
